name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Cordova
      run: npm install -g cordova@latest
      
    - name: Install dependencies
      run: npm install
      
    - name: Add Android platform
      run: cordova platform add android@latest
      
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      
    - name: Install required SDK components
      run: |
        sdkmanager "platform-tools"
        sdkmanager "build-tools;34.0.0"
        sdkmanager "platforms;android-35"
        sdkmanager "cmdline-tools;latest"
      
    - name: Build Android APK (Debug)
      run: cordova build android --debug
      
    - name: Build Android APK (Release)
      run: cordova build android --release
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk