name: Build Android APK (Stable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Cordova
      run: npm install -g cordova@12.0.0
      
    - name: Accept licenses
      run: yes | sdkmanager --licenses
      
    - name: Install SDK components
      run: |
        sdkmanager "platform-tools"
        sdkmanager "build-tools;33.0.2"
        sdkmanager "platforms;android-33"
      
    - name: Clean and reinstall
      run: |
        rm -rf platforms/ plugins/ node_modules/
        npm install
        cordova platform add android@12.0.1
      
    - name: Build APK
      run: cordova build android --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: puzzle-master-apk
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk