name: Build Android APK (Latest)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Cordova latest
      run: npm install -g cordova@latest
      
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      
    - name: Install latest SDK components
      run: |
        sdkmanager "platform-tools"
        sdkmanager "build-tools;35.0.0"
        sdkmanager "platforms;android-35"
        sdkmanager "cmdline-tools;latest"
      
    - name: Clean existing setup
      run: |
        rm -rf platforms/
        rm -rf plugins/
        rm -rf node_modules/
      
    - name: Install dependencies
      run: npm install
      
    - name: Add Android platform
      run: cordova platform add android@14.0.1
      
    - name: Build APK with latest tools
      run: |
        cordova requirements android
        cordova build android --release -- --gradleArg=--no-daemon --gradleArg=--warning-mode=all
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: platforms/android/app/build/outputs/apk/release/*.apk